spring.application.name=desafio-votacao

server.port=${PORT:8080}

logging.file.name=logs/desafio-votacao.log

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=votacao
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=votacao
spring.flyway.schemas=votacao
spring.flyway.create-schemas=true
